### ISSUE TITLE
Don't add space before comma

### ISSUE THREAD

**Issue by tbm** [LaunchPlatform/beancount-black#1]
bean-black made this change:

```
-  Assets:Cash                    1 FOO {10.00 EUR, 2011-12-18}
+  Assets:Cash                                                1 FOO { 10.00 EUR , 2011-12-18 }
```

Note the space before the comma ("EUR , 2011").

bean-black may be opinionated but this is plain wrong.

**Comment by tbm** [comment]
Test case:

```
2000-01-01 open Assets:Cash
2000-01-01 open Equity:Opening-Balance

2022-01-01 * "Opening balance: cash"
  Assets:Cash                    1 FOO {10.00 EUR, 2011-12-18}
  Equity:Opening-Balance
```

**Comment by fangpenlin** [comment]
yeah, well, while it's opinionated formatter, I don't have strong opinion on all the details. In the early stage, I spent most of the time to make it works first. for the comma surrounding style, I agree. for all the programming language I've seen so far, it's always space after comma instead of surrounding. I will make a quick fix for this today or tomorrow
