### ISSUE TITLE
Blows up on certain comments that bean-check is fine with

### ISSUE THREAD

**Issue by peterhoeg** [LaunchPlatform/beancount-black#13]
Using the following sample file:

```beancount
2000-01-01 open Assets:Cash
2000-01-01 open Expenses:Food

;; comment OK

2010-01-01 txn "P. Escobar" "White flour"
  Assets:Cash 1000.00 USD
  Expenses:Food

;; this comment blows up
```
Error message:
```
AttributeError: 'Token' object has no attribute 'data'
```

Removing the last comment makes it OK.

`bean-check` is fine with and without the last comment.

**Comment by fangpenlin** [comment]
Hi, thanks for reporting the issue. The `bean-check` command passing or not has nothing to do beancount-black would work or not. Since the whole beancount-black project is based on top of a standalone beancount file parser we developed and open-sourced:

https://github.com/LaunchPlatform/beancount-parser

So it doesn't not rely on the original beancount code, and it does not validate anything at all. It assumes the beancount file is correct, then just parse it and reformat.

The sample code you provided seems like a legit one. This looks more like a bug in beancount-black itself. I will look into this issue tomorrow.
